# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# SPA routing: send all paths to index.html so React Router works on deep links
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Global security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

    # Content Security Policy — adjust if you embed more third-party resources
    # Note: if you use Supabase, allow its domains for fetch/WebSocket.
    Content-Security-Policy = '''
      default-src 'self';
      img-src 'self' data: https:;
      script-src 'self';
      style-src 'self' 'unsafe-inline';
      font-src 'self' data:;
      connect-src 'self' https://*.supabase.co wss://*.supabase.co;
      frame-ancestors 'none';
      frame-src https://www.youtube.com https://www.youtube-nocookie.com;
    '''

# Long-term caching for hashed build assets (Vite outputs to /assets/)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Prevent caching of the HTML shell to avoid stale deployments
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"